# Generated by Django 4.2.1 on 2023-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50)),
                ('parties_involved', models.TextField()),
                ('court_name', models.CharField(max_length=100)),
                ('previous_hearing', models.DateField(blank=True, null=True)),
                ('next_hearing', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
